### ISSUE TITLE
Error on run:  Could not attach to pid: 547

### ISSUE THREAD

**Issue by Siege097** [pybee/Python-iOS-template#11]
I get this error when I build and run.  The complete error message is:

Could not attach to pid: 547 
cannot attach to process due to System Integrity Protection 

System Integrity Protection is new to OS X El Capitan.  Is this template compatible with OS X El Capitan?  Is there a reason System Integrity Protection would need to be disabled?

Also the program initialized Python runtime successfully but comes up with an error " Unable to locate 'app_name'  main module file" in the console.

**Comment by freakboy3742** [comment]
I haven't done any testing on El Cap, so it's entirely possible there's a problem, or something that needs to be updated. 

To be clear - is this for an iOS project, or an OS X project? I'm just confused why you're getting an OS X SIP error when you're starting iOS code.

**Comment by Siege097** [comment]
Yes, this is for an iOS project.  I disabled the SIP and the error went away, but I am not sure if there would be an issue if you submitted the app to the app store like this.  I guess it depends on what is causing the issue.

**Comment by freakboy3742** [comment]
I believe this has now been addressed; I've successfully been using Sierra and High Sierra to build, simulate, and submit apps to the app store.
