### ISSUE TITLE
Log information problem

### ISSUE THREAD

**Issue by qiang437587687** [pybee/Python-iOS-template#19]
I created the project correctly and run it... but question is how to receive the log message in my code. 

---

const char\* main_script = [[[NSBundle mainBundle] pathForResource:@"Library/ApplicationSupport/zhangPythonBundle.zhangpython/app/zhangpython/app" ofType:@"py"] cStringUsingEncoding:NSUTF8StringEncoding];

FILE\* fd = fopen(main_script, "r");

ret = PyRun_AnyFile(fd, main_script);

---

You know, this code return an int number ‘ret’,  Xcode logs python file message, but I want use a NSString to receive execute result.   Is there  a method or API could  use to solve my question? 

Thank a lot.

**Comment by freakboy3742** [comment]
If the return value is the value you want to display on the console, you can use `NSLog`:

     NSLog(@"The result was: %d\n", ret)

**Comment by qiang437587687** [comment]
OK， first  thanks  for review my request.  Did not say clearly, it is my fault..   

![image](https://cloud.githubusercontent.com/assets/8446305/17578035/f72e699a-5fb6-11e6-8d6c-6d0be0b178c4.png)

**Comment by freakboy3742** [comment]
If I'm understanding you correctly, you need to take a look at [Rubicon](http://rubicon-objc.readthedocs.io/). Rubicon is a bridge between Python and the Objective C runtime, so you can call Objective C methods from inside Python. The sample code you provide here would be achieved with something like:

```
from rubicon.objc import *

UIAlertView = ObjCClass('UIAlertView')
al = UIAlertView.alloc().init()
al.title = "your title here"
al.frame = "Your content here"

al.show()
```

(I haven't tested this specific code snippet, but it should be something very similar to this)

**Comment by freakboy3742** [comment]
We've recently added improved log handling on the iOS template; using the most recent template, anything output to stdout or stderr (with `print()`) will be written to the system log.
