### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by gclsoft** [pybee/Python-iOS-template#2]
```


sent 21 bytes  received 20 bytes  82.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**Comment by dushmantha** [comment]
sent 21 bytes  received 20 bytes  82.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

os- yosemite
iOS version - 8.1
target version - 7.0
2.4 GHz Intel Core i7
