### ISSUE TITLE
Python 3.6.0

### ISSUE THREAD

**Issue by dimaqq** [pybee/Python-iOS-template#23]
It's out, IIRC should be easier to cross-compile tool.

Pretty please :)

**Comment by freakboy3742** [comment]
No disagreement here - I need to sit down and work out what changes are required.

**Comment by dimaqq** [comment]
Any pointers how someone else could go about it?

**Comment by freakboy3742** [comment]
BeeWare iOS tooling now supports Python 3.6 and 3.7.
