### ISSUE TITLE
jasonette + vue.js + django + pybee

### ISSUE THREAD

**Issue by jet10000** [pybee/Python-iOS-template#24]
http://jasonette.com/
https://vuejs.org/
https://www.djangoproject.com/

These projects are enlightening, and we can use pybee to explore iOS and Android like jasonette, and use django to design the server side like vue.js.

**Comment by freakboy3742** [comment]
I'm not sure exactly what you're proposing here. It might be possible to build something similar to Jasonette using BeeWare; but that wouldn't be part of this project, which is a generic iOS template for running *any* Python code on iOS.
