### ISSUE TITLE
Looking for screenshots or examples

### ISSUE THREAD

**Issue by datatalking** [pybee/Python-iOS-template#25]
I'm looking at the repo and it looks like it has potential but there are no photos or pictures of what the app looks like or examples of a gallery etc.

Can you post a few, we are looking at using your code in an app we are looking to build to help disabled children but I have no idea what your code generates.

**Comment by freakboy3742** [comment]
Thanks for the suggestion - but I'm not sure what we'd screenshot. This template produces an Xcode project - the same as any other project you'd produce in Xcode. It doesn't look like anything in particular - the appearance of the app is up to whatever code you write for your app.

The tutorials for [Toga](https://github.com/pybee/toga), on the other hand, *do* include screenshots, as that is a widget toolkit. The tutorial for [Briefcase](https://github.com/pybee/briefcase) also have screenshots, as it's a tool for deploying code as an app. Briefcase uses this project as part of deploying to iOS.

If you've found this project as a result of a search for Python on iOS support, it's probably the wrong place to start - the README points you in the direction of a more helpful starting point.
