### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by someValue** [pybee/Python-iOS-template#6]
can you give me a demo about the python and oc together develop the app for iPhone?
I want to use the python get data and use the oc use data.

Can you hear me?
My English is bad.

**Comment by freakboy3742** [comment]
If you want to use Objective-C APIs, you'll need to use a bridging library - [Rubicon](https://github.com/pybee/rubicon-objc) would be my suggestion. The documentation for that project should give you an idea of how to wrap and/or access an Objective C API. 

The iOS template expects to see a main app class called PythonAppDelegate; beyond that, you just need to write an iOS app as you normally would - but using Python (via Rubicon) to create the classes you need.
